### ISSUE TITLE
PackageInfoHandler.kt:39:40 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver

### ISSUE THREAD

**Issue by qeepcologne** [TrangLeQuynh/flutter-upgrade-version#47]
i am trying to add the dependency but android build (flutter build apk) has failure::
```
e file:///home/bwahlen/.pub-cache/hosted/pub.dev/flutter_upgrade_version-1.1.6/android/src/main/kotlin/com/tranglequynh/flutter_upgrade_version/Pa
ckageInfoHandler.kt:39:40 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'android.content.pm.Applicatio
nInfo?'.
```

i also tried to downgrade kotlin version 2.1.0 => 2.0.21 => 1.9.25, same result.

my workaround is to modify:
```
    "appName" to info.applicationInfo.loadLabel(packageManager).toString(),
```
to
```
    "appName" to info.applicationInfo?.loadLabel(packageManager).toString(),
```

**Comment by TrangLeQuynh** [comment]
Please try this version to check again. I will push new version when there is no more issue.

```yaml
  flutter_upgrade_version:
    git:
      url: https://github.com/TrangLeQuynh/flutter-upgrade-version
      ref: 6e860268ee6a206fb445cf599d61b6e24a6ffd61
```
